import "../static/data/documents/1/Б1ВОД1 Процедурное программирование (готово).docx";
import "../static/data/documents/1/Б1ВОД16 Программная инженерия для корпоративных информационных систем (готово).docx";
import "../static/data/documents/2/Б2П1 Практика по получению профессиональных умений и опыта профессиональной деятельности (готово).doc";
import "../static/data/documents/3/Б1Б11 Структура и алгоритмы обработки данных (готово).docx";
import "../static/data/documents/3/Б2П1 Практика по получению профессиональных умений и опыта профессиональной деятельности (готово).doc";
import "../static/data/documents/4/Б1Б11 Структура и алгоритмы обработки данных (готово).docx";
import "../static/data/documents/4/Б1Б19 Информационные системы и технологии (готово).docx";
import "../static/data/documents/4/Б1ВДВ8_1 Открытые информационные системы (готово).doc";
import "../static/data/documents/4/Б1ВДВ8_2 Методы функциональной стандартизации (готово).doc";
import "../static/data/documents/4/Б1ВОД3 Разработка программных приложений (готово).docx";
import "../static/data/documents/4/Б1ВОД15 Качество, стандартизация и сертификация информационных систем (готово).doc";
import "../static/data/documents/4/Б2П1 Практика по получению профессиональных умений и опыта профессиональной деятельности (готово).doc";
import "../static/data/documents/5/Б1Б19 Информационные системы и технологии (готово).docx";
import "../static/data/documents/5/Б1ВДВ4_1 Корпоративные информационные системы (готово).docx";
import "../static/data/documents/5/Б1ВДВ4_2 Интерфейсы информационных систем (готово).docx";
import "../static/data/documents/5/Б1ВДВ5_1 Оценка качества информационных систем (готово).docx";
import "../static/data/documents/5/Б1ВДВ5_2 Сертификация информационных систем (готово).docx";
import "../static/data/documents/5/Б1ВДВ6_2 Математические основы защиты информации (готово).docx";
import "../static/data/documents/5/Б1ВДВ10_1 Сопровождение информационных систем (готово).docx";
import "../static/data/documents/5/Б1ВДВ11_2 Математические методы в информационных технологиях (готово).docx";
import "../static/data/documents/5/Б1ВОД4 Разработка клиент-серверных приложений (готово).docx";
import "../static/data/documents/5/Б2П1 Практика по получению профессиональных умений и опыта профессиональной деятельности (готово).doc";
import "../static/data/documents/6/Б1Б10 Анализ сложности алгоритмов (готово).docx";
import "../static/data/documents/6/Б1ВДВ6_1 Информационная безопасность и защита информации (готово).doc";
import "../static/data/documents/6/Б1ВДВ7_1 Технологии визуализации информации (готово).docx";
import "../static/data/documents/6/Б1ВДВ7_2 Проектирование графических моделей (готово).docx";
import "../static/data/documents/6/Б1ВДВ9_1 Системы электронного документооборота (готово).docx";
import "../static/data/documents/6/Б1ВОД8 Теория систем и системный анализ (готово).docx";
import "../static/data/documents/6/Б1ВОД9 Моделирование систем (готово).doc";
import "../static/data/documents/6/Б1ВОД10 Интеллектуальные системы и технологии (готово).docx";
import "../static/data/documents/6/Б2П1 Практика по получению профессиональных умений и опыта профессиональной деятельности (готово).doc";
import "../static/data/documents/7/Б1ВДВ9_2 Мультиагентные информационные системы (готово).docx";
import "../static/data/documents/7/Б1ВДВ11_1 Информац-поисковые системы (готово).doc";
import "../static/data/documents/7/Б1ВОД7 Проектирование информационных систем (готово).doc";
import "../static/data/documents/7/Б1ВОД11 Мировые информационные ресурсы (готово).docx";
import "../static/data/documents/7/Б1ВОД12 Управление ИТ-проектами (готовое).docx";
import "../static/data/documents/7/Б1ВОД13 Безопасность функционирования информационных систем (готово).docx";
import "../static/data/documents/7/Б1ВОД14 Разработка программного обеспечения для корпоративных информационных систем (готово).doc";
import "../static/data/documents/7/Б2П1 Практика по получению профессиональных умений и опыта профессиональной деятельности (готово).doc";
import "../static/data/documents/8/Б1ВДВ10_2 Менеджмент информационных систем (готово).docx";
import "../static/data/documents/8/Б2Г1 Государственный экзамен (готово).doc";
import "../static/data/documents/8/Б2Д1 Выпускная квалификационная работа (готово).doc";
import "../static/data/documents/8/Б2П2 Преддипломная практика(готово).doc";
